import os
import json
from pypdf import PdfWriter, PdfReader

# ================= CONFIGURATION =================
# Directory containing the PDFs generated by your EA script
SOURCE_DIR = r"D:\PROJECTS\IDPS\pdfs" 

# Output filename for the merged PDF
OUTPUT_PDF = r"D:\PROJECTS\IDPS\Combined_Knowledge_Graph.pdf"

# Output filename for the JSON mapping (for the LLM)
OUTPUT_MAP = r"D:\PROJECTS\IDPS\pdf_page_mapping.json"
# =================================================

def merge_pdfs_and_create_map(source_dir, output_pdf_path, output_map_path):
    writer = PdfWriter()
    page_mapping = {}
    
    # Get all PDF files and sort them to ensure consistent order
    # You might want to sort by creation time or name
    pdf_files = [f for f in os.listdir(source_dir) if f.lower().endswith('.pdf')]
    pdf_files.sort() 

    current_page_index = 0

    print(f"Found {len(pdf_files)} PDF files. Merging...")

    for filename in pdf_files:
        file_path = os.path.join(source_dir, filename)
        
        try:
            reader = PdfReader(file_path)
            num_pages = len(reader.pages)
            
            # If the file is empty or corrupted, skip it
            if num_pages == 0:
                print(f"Skipping empty file: {filename}")
                continue

            # 1. Add PDF to the merger
            writer.append(reader)
            
            # 2. Add a Bookmark in the PDF (Helpful for humans)
            # Pointing to the start of this section
            writer.add_outline_item(title=filename, page_number=current_page_index)

            # 3. Create Mapping for the LLM
            # We record the original filename, start page, and end page.
            # Note: Pages are 1-based for human/LLM readability here.
            page_mapping[filename] = {
                "start_page": current_page_index + 1,
                "end_page": current_page_index + num_pages,
                "total_pages": num_pages
            }

            current_page_index += num_pages
            print(f"Merged: {filename} (Pages {page_mapping[filename]['start_page']}-{page_mapping[filename]['end_page']})")

        except Exception as e:
            print(f"Error merging {filename}: {e}")

    # Save the Merged PDF
    with open(output_pdf_path, "wb") as f_out:
        writer.write(f_out)
    print(f"\nSuccessfully saved merged PDF: {output_pdf_path}")

    # Save the JSON Mapping
    with open(output_map_path, "w", encoding='utf-8') as f_json:
        json.dump(page_mapping, f_json, indent=4)
    print(f"Successfully saved page mapping: {output_map_path}")

if __name__ == "__main__":
    if os.path.exists(SOURCE_DIR):
        merge_pdfs_and_create_map(SOURCE_DIR, OUTPUT_PDF, OUTPUT_MAP)
    else:
        print(f"Error: Source directory not found: {SOURCE_DIR}")